#!/bin/sh -e

autoreconf -if

cpt l texinfo || export MAKEINFO=true

export LDFLAGS="$LDFLAGS -static"

./configure \
    --prefix=/usr \
    --disable-webkit \
    --disable-rpath \
    --disable-shared

make
make DESTDIR="$1" install
