#!/bin/sh -e

(
    cd termkey

    make termkey.h libtermkey.la

    mkdir -p "../usr/lib" \
             "../usr/include"

    mv termkey.h "../usr/include"
    mv .libs/*.a "../usr/lib"

)

(
    # Lpeg doesn't have an option to create static libraries.
    cd lpeg
    for obj in lpcap lpcode lpprint lptree lpvm; do
        "${CC:-cc}" $CFLAGS -c -o $obj.o $obj.c
    done
    ar rcs ../usr/lib/liblpeg.a ./*.o
)

(
    cd vis

    export CFLAGS="$CFLAGS -static -I../usr/include"
    export LDFLAGS="$LDFLAGS -L../usr/lib"

    ./configure \
        --prefix=/usr \
        --enable-lua \
        --enable-liblpeg-static

    make
    make DESTDIR="$1" install
)
