#!/bin/sh -e

cat <<EOF

  [1mIMPORTANT:[m

    Please keep in mind that this is a fork of KISS
    and not the original upstream (although this is
    not a huge alteration from it). Send your issues
    to me <cem at ckyln dot com>.

EOF
